smart_driver/driver_app/urls.py
from django.conf.urls import url
from . import views

app_name = 'driver_app'

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^profile/', views.profile, name="profile"),
    url(r'^logout/$', views.logout_view, name='logout'),
]

smart_driver/smart_driver/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework import routers
from driver_app import views


router = routers.DefaultRouter()
router.register(r'rides', views.RideViewSet)
router.register(r'week_statements', views.WeekStatementViewSet)
router.register(r'day_statements', views.DayStatementViewSet)
router.register(r'drivers', views.DriverViewSet)
router.register(r'month_statements', views.MonthStatementViewSet)


urlpatterns = [
    url(r'^', include('driver_app.urls')),
    url(r'^api/', include(router.urls)),
    url(r'^admin/', include(admin.site.urls)),
]

smart_driver/driver_app/models.py
import json
import re
import datetime
import dateutil.parser
from dateutil.tz import gettz
from dateutil.relativedelta import relativedelta
from decimal import Decimal
from django.db import models
from django.db.models import Min, Max, Sum, Avg
from django.contrib.auth.models import User


class Ride(models.Model):
    driver = models.ForeignKey('Driver', on_delete=models.CASCADE)
    week_statement = models.ForeignKey('WeekStatement',
                                       on_delete=models.CASCADE, null=True)
    day_statement = models.ForeignKey('DayStatement',
                                      on_delete=models.CASCADE, null=True)
    month_statement = models.ForeignKey('MonthStatement',
                                        on_delete=models.CASCADE, null=True)
    trip_id = models.CharField(max_length=50, primary_key=True)
    status = models.CharField(max_length=15)
    total_earned = models.DecimalField(max_digits=8, decimal_places=2)
    distance = models.DecimalField(max_digits=7, decimal_places=2)
    date = models.DateField()
    request_at = models.DateTimeField()
    begintrip_at = models.DateTimeField(null=True)
    dropoff_at = models.DateTimeField(null=True)
    duration = models.DurationField()

    def get_stats(self, ride_data, time_zone):
        self.date = dateutil.parser.parse(ride_data['date']).date()

        self.status = ride_data['status']
        if self.status not in ['canceled', 'driver_canceled']:
            self.begintrip_at = dateutil.parser.parse(ride_data['begintrip_at'])
            self.begintrip_at = self.begintrip_at.replace(tzinfo=time_zone)
            self.dropoff_at = dateutil.parser.parse(ride_data['dropoff_at'])
            self.dropoff_at = self.dropoff_at.replace(tzinfo=time_zone)

        self.total_earned = Decimal(ride_data['total_earned'])
        self.distance = Decimal(ride_data['distance'])
        self.request_at = dateutil.parser.parse(ride_data['request_at'])
        self.request_at = self.request_at.replace(tzinfo=time_zone)
        self.duration = datetime.timedelta(seconds=float(ride_data['duration']))
        self.save()

    def assign_month(self, months):
        for m in months:
            if self.date.month == m.starting_at.month:
                self.month_statement = m
        if not self.month_statement:
            new_month_start = self.date.replace(day=1)
            self.month_statement, c = MonthStatement.objects.get_or_create(
                driver=self.driver,
                starting_at=new_month_start,
                ending_at=new_month_start + relativedelta(day=31),
                month_name=new_month_start.strftime('%B \'%y')
            )
            months.append(self.month_statement)
        self.save()
        return months

    def assign_week(self, weeks):
        for w in weeks:
            if w.starting_at <= self.date <= w.ending_at:
                self.week_statement = w
        if not self.week_statement:
            self.week_statement, c = WeekStatement.objects.get_or_create(
                driver=self.driver,
                starting_at=self.date,
                ending_at=self.date + datetime.timedelta(days=6)
            )
            weeks.append(self.week_statement)
        self.save()
        return weeks

    def assign_day(self, days):
        for d in days:
            if self.date == d.date:
                self.day_statement = d
        if not self.day_statement:
            self.day_statement, c = DayStatement.objects.get_or_create(
                driver=self.driver,
                date=self.date,
                weekday=self.date.weekday(),
                week_statement=self.week_statement,
                month_statement=self.month_statement
            )
            days.append(self.day_statement)
        self.save()
        return days


class DayStatement(models.Model):
    WEEKDAY_CHOICES = ((0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'),
                       (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'),
                       (6, 'Sunday'))
    driver = models.ForeignKey('Driver', on_delete=models.CASCADE)
    total_rides = models.IntegerField(default=0, null=True)
    total_earned = models.DecimalField(max_digits=8, decimal_places=2,
                                       null=True)
    date = models.DateField()
    weekday = models.IntegerField(choices=WEEKDAY_CHOICES, default=0)
    time_worked = models.DurationField(null=True)
    rate_per_ride = models.DecimalField(max_digits=8, decimal_places=2,
                                        null=True)
    rate_per_hour = models.DecimalField(max_digits=8, decimal_places=2,
                                        null=True)
    week_statement = models.ForeignKey('WeekStatement',
                                       on_delete=models.CASCADE, null=True)
    month_statement = models.ForeignKey('MonthStatement',
                                        on_delete=models.CASCADE, null=True)

    def calculate_day_stats(self):
        self.total_rides = self.ride_set.count()
        aggs = self.ride_set.aggregate(Sum('total_earned'),
                                       Min('request_at'),
                                       Max('dropoff_at'))

        self.total_earned = aggs['total_earned__sum']
        self.rate_per_ride = self.total_earned / self.total_rides

        earliest_request = aggs['request_at__min']
        latest_dropoff = aggs['dropoff_at__max']
        if latest_dropoff:
            self.time_worked = latest_dropoff - earliest_request
            hours = round(Decimal(self.time_worked.total_seconds() / 3600), 2)
            self.rate_per_hour = round((self.total_earned / hours), 2)
        self.save()


class WeekStatement(models.Model):
    driver = models.ForeignKey('Driver', on_delete=models.CASCADE)
    starting_at = models.DateField(null=True, unique=True)
    ending_at = models.DateField(null=True, unique=True)
    total_earned = models.DecimalField(max_digits=8, decimal_places=2,
                                       null=True)
    rate_per_ride = models.DecimalField(max_digits=8, decimal_places=2,
                                        null=True)
    rate_per_hour = models.DecimalField(max_digits=8, decimal_places=2,
                                        null=True)
    rate_per_day = models.DecimalField(max_digits=8, decimal_places=2,
                                       null=True)
    total_rides = models.IntegerField(default=0, null=True)
    statement_id = models.CharField(max_length=75, null=True, unique=True)
    month_statement = models.ManyToManyField('MonthStatement')

    def associate_months(self, months):
        for month in months:
            if month.starting_at.month in [self.starting_at.month,
                                           self.ending_at.month]:
                self.month_statement.add(month)
                self.save()

    def calculate_week_stats(self):
        days = self.daystatement_set.count()
        if days:
            aggs = self.daystatement_set.aggregate(Sum('total_earned'),
                                                   Sum('total_rides'),
                                                   Avg('rate_per_hour'))
            self.total_earned = aggs['total_earned__sum']
            self.total_rides = aggs['total_rides__sum']
            self.rate_per_ride = self.total_earned / self.total_rides
            self.rate_per_hour = aggs['rate_per_hour__avg']
            self.rate_per_day = self.total_earned / days
            self.save()


class MonthStatement(models.Model):
    driver = models.ForeignKey('Driver', on_delete=models.CASCADE)
    starting_at = models.DateField()
    ending_at = models.DateField()
    month_name = models.CharField(max_length=15)
    total_earned = models.DecimalField(max_digits=8, decimal_places=2,
                                       null=True)
    rate_per_ride = models.DecimalField(max_digits=8, decimal_places=2,
                                        null=True)
    rate_per_hour = models.DecimalField(max_digits=8, decimal_places=2,
                                        null=True)
    rate_per_day = models.DecimalField(max_digits=8, decimal_places=2,
                                       null=True)
    total_rides = models.IntegerField(default=0, null=True)

    def calculate_month_stats(self):
        days = self.daystatement_set.count()
        if days:
            aggs = self.daystatement_set.aggregate(Sum('total_earned'),
                                                   Sum('total_rides'),
                                                   Avg('rate_per_hour'))
            self.total_earned = aggs['total_earned__sum']
            self.total_rides = aggs['total_rides__sum']
            self.rate_per_ride = self.total_earned / self.total_rides
            self.rate_per_day = self.total_earned / days
            self.rate_per_hour = aggs['rate_per_hour__avg']
            self.save()


class Driver(models.Model):
    u_user_id = models.CharField(max_length=50)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField()
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)

    def get_name(self):
        return self.first_name.title() + ' ' + self.last_name.title()

    @staticmethod
    def get_csrf_token(session):
        login_response = session.get('https://login.uber.com/login')
        csrf_token_pattern = (
            'type="hidden" name="_csrf_token" value="([a-zA-Z0-9\_\-\=]+)">')
        csrf_token = re.search(
            csrf_token_pattern, login_response.text).group(1)
        return csrf_token

    @staticmethod
    def login(session, request):
        csrf_token = Driver.get_csrf_token(session)
        data = {
            'email': request.POST['email'],
            'password': request.POST['password'],
            '_csrf_token': csrf_token,
            'access_token': ''
        }

smart_driver/driver_app/views.py
import json
import requests
from django.shortcuts import render
from rest_framework import viewsets
from django.http import HttpResponseRedirect
from django.db.models import Avg
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from .serializers import RideSerializer, DayStatementSerializer
from .serializers import WeekStatementSerializer, MonthStatementSerializer
from .serializers import DriverSerializer
from .models import Ride, DayStatement, WeekStatement, MonthStatement, Driver


class RideViewSet(viewsets.ModelViewSet):
    queryset = Ride.objects.all()
    serializer_class = RideSerializer


class DayStatementViewSet(viewsets.ModelViewSet):
    queryset = DayStatement.objects.filter(total_earned__gt=0)
    serializer_class = DayStatementSerializer

    def get_queryset(self):
        queryset = DayStatement.objects.filter(
            total_earned__gt=0).order_by('-date')
        driver_id = self.request.query_params.get('driver', None)
        month = self.request.query_params.get('month', None)
        weekday = self.request.query_params.get('weekday', None)
        if driver_id:
            queryset = queryset.filter(driver=Driver.objects.get(id=driver_id))
        if month:
            queryset = queryset.filter(
                month_statement=MonthStatement.objects.get(month_name=month))
        if weekday:
            for tup in DayStatement.WEEKDAY_CHOICES:
                if tup[1] == weekday:
                    queryset = queryset.filter(weekday=tup[0])
        return queryset


class WeekStatementViewSet(viewsets.ModelViewSet):
    queryset = WeekStatement.objects.filter(total_earned__gt=0)
    serializer_class = WeekStatementSerializer

    def get_queryset(self):
        queryset = WeekStatement.objects.filter(
            total_earned__gt=0).order_by('-starting_at')
        driver_id = self.request.query_params.get('driver', None)
        month = self.request.query_params.get('month', None)
        if driver_id:
            queryset = queryset.filter(driver=Driver.objects.get(id=driver_id))
        if month:
            queryset = queryset.filter(
                month_statement=MonthStatement.objects.get(month_name=month))
        return queryset


class DriverViewSet(viewsets.ModelViewSet):
    queryset = Driver.objects.all()
    serializer_class = DriverSerializer


class MonthStatementViewSet(viewsets.ModelViewSet):
    queryset = MonthStatement.objects.filter(
        total_earned__gt=0).order_by('-starting_at')
    serializer_class = MonthStatementSerializer


def pretty_print_POST(req):
    return '{}\n{}\n{}\n\n{}'.format(
        '-----------START-----------',
        req.method + ' ' + req.url,
        '\n'.join('{}: {}'.format(k, v) for k, v in req.headers.items()),
        req.body,
    )


def home(request):
    context = {}
    if request.POST:
        username = request.POST['email']

        session = requests.Session()
        login_response = Driver.login(session, request)

        if login_response.status_code == 200:
            user, created = User.objects.get_or_create(username=username)

            user.backend = 'django.contrib.auth.backends.ModelBackend'
            login(request, user)

            ids = Driver.get_statement_ids(login_response)

            if created:
                driver = Driver(user=user, email=username)
                driver.get_u_user_id(login_response)
                driver.get_first_name(login_response)
                driver.get_last_name(login_response)
                driver.save()

            else:
                driver = Driver.objects.get(user=user)
                ids = driver.get_new_statement_ids(ids)

            driver.grab_data(session, ids)
            return HttpResponseRedirect("/profile/")

        else:
            print('login_failed')
            context = {
                'fail': (login_response.status_code, login_response.reason)}

    return render(request, "driver_app/home.html", context)


def profile(request):
    driver = Driver.objects.get(user=request.user)
    day_statements = DayStatement.objects.filter(
        driver=driver).filter(total_earned__gt=0)

    hourly_rate_by_weekday = {'key': "Hourly Rate By Weekday", 'values': []}

    rate_avgs = day_statements.values('weekday').annotate(
        avg=Avg('rate_per_hour'))
    rate_avgs = sorted(rate_avgs, key=lambda lil_dict: lil_dict['weekday'])
    max_avg = max(rate_avgs, key=lambda lil_dict: lil_dict['avg'])['avg']
    hourly_rate_by_weekday['values'] = [{
        "label": dict(DayStatement.WEEKDAY_CHOICES)[day_dict['weekday']],
        "value": round(day_dict['avg'], 2)
        } for day_dict in rate_avgs]

    context = {'weekday_graph_data': json.dumps(hourly_rate_by_weekday),
               'hourly_max': round(max_avg)}
    return render(request, "driver_app/profile.html", context)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect("/")

smart_driver/driver_app/templates/driver_app/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static 'driver_app/assets/ico/blk_favicon.ico' %}" type="image/x-icon">
    <title>Smart Driver</title>

    <!-- Bootstrap core CSS -->
    <link href="static/driver_app/assets/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="static/driver_app/assets/css/style.css" rel="stylesheet">
    <link href="static/driver_app/assets/css/font-awesome.min.css" rel="stylesheet">

  </head>
  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="">Smart Driver</a>
        </div>
        <div class="navbar-collapse collapse navbar-right">
          <ul class="nav navbar-nav">
            {% if user.is_authenticated %}
            <li ><a id="logout" href="{% url 'driver_app:logout' %}">Logout</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

	<!-- *****************************************************************************************************************
	 HEADERWRAP
	 ***************************************************************************************************************** -->
	  <div id="headerwrap">
	    <div class="container">
  	    <div class="row">
  		    <div class="col-lg-8 col-lg-offset-2">
            <img src="static/driver_app/assets/img/smart_driver_logo.png" alt="Smart Driver" />
              <h2>
                Welcome to <span style="color:white;">Smart Driver</span>
                - the only app that helps Uber drivers maximize efficiency
                with state-of-the-art data analysis.
              </h2>
        {% if not user.is_authenticated %}
              </br>
              {% if fail %}
              <h3>
                Error: {{fail}}
              <br>
                Uber rejected your request. Make sure you are using the
                same email and password you use to log in to Uber.
              </h3>
              {% else %}
  		        <h3>Please log in below with your Uber credentials.</h3>
              {% endif %}
	        </div><!-- col-lg-8 col-lg-offset-2 -->
  <!-- *****************************************************************************************************************
  LOG-IN FORM
  ************************************************************************************************************** -->
          <form class="form-login" method="post" action="">{% csrf_token %}
            <div class="form-log-in-with-email">
              <div class="form-white-background">

                <div class="form-title-row">
                </div>

                <div class="form-row">
                  <label><span>Email</span></label>
                  <input type="email" name="email">
                </div><!-- form-row -->

                <div class="form-row">
                  <label><span>Password</span></label>
                  <input type="password" name="password">
                </div><!-- form-row -->

                <div class="form-row">
                  <button type="submit">Log in</button>
                </div><!-- form-row -->

              </div><!-- form-white-background -->
            </div><!-- form-log-in-with-email -->
          </form><!-- form-login -->
        {% else %}<!-- user.is_authenticated -->
            <br>
            <br>
            <br>
            <br>
            <a href="{% url 'driver_app:profile' %}"><h1>Return to your profile</h1></a>
          </div><!-- col-lg-8 col-lg-offset-2 -->
        {% endif %}
		    </div><!-- /row -->
      </div>
	  </div><!-- /headerwrap -->
<!-- *****************************************************************************************************************
 FOOTER
***************************************************************************************************************** -->
	  <div id="footerwrap">
	    <div class="container">
		    <div class="row">

          <div class="col-lg-4">
            <h4>About</h4>
    			  <div class="hline-w"></div>
    			  <p>Smart Driver is a dynamic app that helps Uber drivers maximize effiency via cutting-edge data analysis.</p>
    		  </div><!-- col-lg-4 -->

          <div class="col-lg-4">
      			<h4>Project GitHub</h4>
      			<div class="hline-w"></div>
      			<p>
      			<a target="_blank" href="https://github.com/Smart-Driver/smart-driver-app"><i class="fa fa-github"></i></a>
      			</p>
          </div><!-- col-lg-4 -->

    		  <div class="col-lg-4">
      			<h4>Smart Driver Team</h4>
      			<div class="hline-w"></div>
      			<p>
      			  Julio Cardoza<br>
      			  Kathryn Jackson<br>
              Ryan Oakes<b>
      			</p>
          </div><!-- col-lg-4 -->

		    </div><!--/row -->
	    </div><!--/container -->
	  </div><!--/footerwrap -->
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="static/driver_app/assets/js/bootstrap.min.js"></script>
	  <script src="static/driver_app/assets/js/retina-1.1.0.js"></script>
    <script src="static/driver_app/assets/js/jquery.hoverdir.js"></script>
	  <script src="static/driver_app/assets/js/jquery.hoverex.min.js"></script>
	  <script src="static/driver_app/assets/js/jquery.prettyPhoto.js"></script>
	  <script src="static/driver_app/assets/js/custom.js"></script>

  </body>
</html>

smart_driver/driver_app/templates/driver_app/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static 'driver_app/assets/ico/blk_favicon.ico' %}" type="image/x-icon">

    <title>Smart Driver</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/driver_app/assets/css/bootstrap.css" rel="stylesheet">
    <link href="/static/driver_app/assets/css/qtip.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/driver_app/assets/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.css">
    <link href="/static/driver_app/assets/d3/nv.d3.css" rel="stylesheet" type="text/css">
    <link href="/static/driver_app/assets/css/style.css" rel="stylesheet">

  </head>
  
  <body>
<!-- ***************************************************************************
  HEADERWRAP
*****************************************************************************-->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="../">Smart Driver</a>
        </div><!-- /navbar-collapse collapse navbar-right-->
        <div class="navbar-collapse collapse navbar-right">
          <ul class="nav navbar-nav">
            {% if user.is_authenticated %}
              <li ><a id="logout" href="{% url 'driver_app:logout' %}">Logout</a></li>
            {% endif %}
          </ul>
        </div><!-- /navbar-collapse collapse navbar-right-->
      </div><!-- /container -->
    </div><!-- /navbar navbar-default navbar-fixed-top -->
<!-- ***************************************************************************
MAIN BODY
***************************************************************************************************************** -->
    <div id="headerwrap">
      <div class="container">
        <div class="col-lg-8 col-lg-offset-2">
          <input id="driver_id" type="hidden" value={{user.driver.id}}>
          <h2>Welcome <span style="color:white;">{{ user.driver.get_name }}</span>!</h2>
          <br>
          <br>
        </div><!-- /col-lg-8 col-lg-offset-2 -->
<!-- ***************************************************************************
CHARTS
***************************************************************************************************************** -->
        <div class="row">
<!-- ***************************************************************************
WEEKDAY GRAPH
***************************************************************************************************************** -->
          <div class="graph">
            <div id="chart2">
              <h2>Monthly Income ($)</h2>
              <svg></svg>
            </div><!-- /chart1 -->
          </div><!-- col-xs-6" -->
<!-- ***************************************************************************
ANNUAL GRAPH
***************************************************************************************************************** -->
          <div class="graph">
            <div id="chart1">
              <h2>Average Hourly Rate ($)</h2>
              <svg></svg>
            </div><!-- /chart1 -->
          </div><!-- col-xs-6" -->
        </div><!--row -->
<!-- ***************************************************************************
INFO BOXES
***************************************************************************************************************** -->
        <div id="cwrap" class="container">
          <div class="row centerd">

            <div class="col-xs-3 info_box" id="avg_per_hour">
              <h3>Avg Hourly Rate</h3>
              <p>123</p>
            </div><!-- /col-xs-3 info_box -->

            <div class="col-xs-3 info_box" id="avg_per_unit">
              <h3>Avg Daily Rate</h3>
              <p>456</p>
            </div><!-- /col-xs-3 info_box -->

            <div class="col-xs-3 info_box" id="total_earned">
              <h3>Total Earned</h3>
              <p>789</p>
            </div><!-- /col-xs-3 info_box -->

          </div><!-- /row centered -->
        </div><!--/cwrap -->
<!-- *****************************************************************************************************************
DYNAMIC USER TABLE
***************************************************************************************************************** -->
        <div class="form-login" method="post" action="#">
          <div class="table">
            <select id="data-type" class="table-decorator btn btn-theme">
              <option selected=0 value="daily">Daily</option>
              <option value="weekly">Weekly</option>
            </select>

            <button id="reset" type="button" class="table-decorator btn btn-theme">
              Show all
            </button>

            <table id="table_id" class="display" width="100%">
              <thead>
                <tr></tr>
              </thead>
            </table>

          </div><!-- /table -->
        </div><!-- /form-login -->
      </div> <!-- /container -->
    </div><!-- /headerwrap -->
<!-- ***************************************************************************
FOOTER
***************************************************************************************************************** -->
    <div id="footerwrap">
      <div class="container">
        <div class="row">

          <div class="col-lg-4">
            <h4>About</h4>
            <div class="hline-w"></div>
            <p>Smart Driver is a dynamic app that helps Uber drivers maximize effiency via cutting-edge data analysis.</p>
          </div><!-- /col-lg-4 -->

          <div class="col-lg-4">
            <h4>Project GitHub</h4>
            <div class="hline-w"></div>
            <p>
              <a target="_blank" href="https://github.com/Smart-Driver/smart-driver-app"><i class="fa fa-github"></i></a>
            </p>
          </div><!-- /col-lg-4 -->

          <div class="col-lg-4">
            <h4>Smart Driver Team</h4>
    			  <div class="hline-w"></div>
			      <p>
			        Julio Cardoza<br/>
			        Kathryn Jackson<br/>
              Ryan Oakes<br/>
            </p>
          </div><!-- /col-lg-4 -->

        </div><!-- /row -->
      </div> <!-- /container -->
    </div><!-- /footerwrap -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.2/d3.min.js" charset="utf-8"></script>
    <script src="/static/driver_app/assets/d3/nv.d3.js"></script>
    <script type="text/javascript" src="/static/driver_app/qtip.min.js"></script>
    <script src="/static/driver_app/assets/js/jquery.dataTables.js"></script>
    <script src="/static/driver_app/assets/js/bootstrap.min.js"></script>
    <script src="/static/driver_app/assets/js/retina-1.1.0.js"></script>
    <script src="/static/driver_app/assets/js/jquery.hoverdir.js"></script>
    <script src="/static/driver_app/assets/js/jquery.hoverex.min.js"></script>
    <script src="/static/driver_app/assets/js/jquery.prettyPhoto.js"></script>
    <script src="/static/driver_app/assets/js/custom.js"></script>
    <script src="/static/driver_app/data_table.js"></script>
    <script src="/static/driver_app/assets/d3/nv.d3.js"></script>
    <script src="/static/driver_app/graphs.js"></script>
  </body>
</html>